"""
Auditor Agent — "The Debugger"
Takes the errors found by Explorer and maps them to exact source code lines.
Returns a list of structured bug reports with suggested fixes.

FIX APPLIED: The RepoGuardian Analyst prompt has been integrated here
as the Gemini system instruction, giving you the scoring and structured
output described in the prompt.
"""

import os
import json
import re
from typing import Optional

import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

CODE_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".py", ".vue", ".svelte"}
IGNORED_DIRS = {"node_modules", ".git", "__pycache__", ".next", "dist", "build"}
MAX_FILE_SIZE = 5000  # chars per file sent to LLM

# RepoGuardian Analyst system instruction (integrated from your prompt)
ANALYST_SYSTEM_PROMPT = """You are RepoGuardian Analyst AI.
Your responsibility is to analyze GitHub repositories and identify software quality issues.
Objectives:
1. Analyze repository structure and architecture.
2. Detect: Bugs, Runtime risks, Null pointer issues, Exception handling problems, Unused code, Performance bottlenecks, Maintainability concerns.
3. For each issue provide: Issue ID, Issue Title, File Name, Severity Level, Explanation, Recommended Fix, Estimated Impact.
4. Generate: Repository Summary, Repository Health Score (0-100), Code Quality Score, Maintainability Score, Documentation Score, Security Score.
5. Highlight: Strengths, Weaknesses, Opportunities for improvement.
6. Generate pull request suggestions for accepted fixes.
Rules: Never invent files that do not exist. Do not claim certainty when confidence is low. Prioritize actionable recommendations. Focus on developer productivity and code quality. Output structured JSON-compatible data whenever possible."""

# RepoGuardian Reviewer system instruction (integrated from your prompt)
REVIEWER_SYSTEM_PROMPT = """You are RepoGuardian Reviewer AI.
Your responsibility is to independently review and validate the findings generated by the Analyst AI.
Objectives:
1. Review all identified issues.
2. Evaluate proposed fixes.
3. Determine whether each fix: Fully resolves the issue, Partially resolves the issue, Introduces potential risks.
4. Assign: Confidence Score (0-100), Risk Level, Review Verdict.
5. Explain: Why the fix is valid, Potential side effects, Alternative approaches.
6. Produce: Approval Recommendation, Developer Notes, Final Review Summary.
Verdicts: Approved, Approved with Caution, Needs Review, Rejected.
Rules: Be critical but constructive. Validate logic, not assumptions. Highlight risks and edge cases. Never blindly approve recommendations. Provide concise explanations suitable for dashboard display."""


def _extract_json_array(text: str) -> list:
    """
    Robustly extract a JSON array from LLM output.
    Handles markdown fences, leading/trailing text, etc.
    """
    # Strip markdown code fences
    clean = re.sub(r"```(?:json)?", "", text).replace("```", "").strip()

    # Try direct parse
    try:
        result = json.loads(clean)
        if isinstance(result, list):
            return result
        if isinstance(result, dict) and "bugs" in result:
            return result["bugs"]
    except json.JSONDecodeError:
        pass

    # Find first [...] block
    m = re.search(r"\[[\s\S]*?\]", clean)
    if m:
        try:
            result = json.loads(m.group())
            if isinstance(result, list):
                return result
        except json.JSONDecodeError:
            pass

    # Find all {...} blocks (fallback: treat each as a bug)
    objects = re.findall(r"\{[^{}]+\}", clean)
    bugs = []
    for obj in objects:
        try:
            bugs.append(json.loads(obj))
        except json.JSONDecodeError:
            pass
    return bugs


def _read_source_files(repo_path: str) -> dict[str, str]:
    """Read all source code files."""
    files = {}
    for root, dirs, filenames in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
        for fname in filenames:
            if any(fname.endswith(ext) for ext in CODE_EXTENSIONS):
                full_path = os.path.join(root, fname)
                rel_path = os.path.relpath(full_path, repo_path)
                try:
                    with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()
                    files[rel_path] = content
                except Exception:
                    pass
    return files


def _format_errors_for_prompt(console_errors: list, network_errors: list) -> str:
    lines = []
    for i, err in enumerate(console_errors[:20]):
        lines.append(f"  [{i+1}] [{err.get('type', 'error')}] {err.get('text', '')[:300]}")
        if err.get('location'):
            lines.append(f"       at: {err['location']}")
    for i, err in enumerate(network_errors[:10]):
        lines.append(f"  [NET-{i+1}] FAILED REQUEST: {err.get('url', '')} — {err.get('failure', '')}")
    return "\n".join(lines) if lines else "No runtime errors detected."


def audit_errors(explorer_result: dict, repo_path: str) -> list:
    """
    Map runtime errors to source code and generate fix suggestions.
    Returns a list of bug objects.
    """
    console_errors = explorer_result.get("console_errors", [])
    network_errors = explorer_result.get("network_errors", [])

    # If no errors at all, still do a basic static scan
    all_errors_empty = not console_errors and not network_errors
    if all_errors_empty:
        return _static_bug_scan(repo_path)

    source_files = _read_source_files(repo_path)
    if not source_files:
        return []

    # Pick the most relevant files (not all of them — LLM context limit)
    priority_files = {}
    other_files = {}
    for path, content in source_files.items():
        if any(seg in path for seg in ("src/", "app/", "components/", "pages/", "lib/")):
            priority_files[path] = content
        else:
            other_files[path] = content

    # Build truncated source context (stay under ~40000 chars, slicing strictly at line boundaries)
    source_context = []
    char_budget = 40000
    for path, content in {**priority_files, **other_files}.items():
        lines = content.splitlines()
        file_snippet_lines = []
        current_len = 0
        for line in lines:
            if current_len + len(line) + 1 > 4000:
                break
            file_snippet_lines.append(line)
            current_len += len(line) + 1
        
        file_snippet = "\n".join(file_snippet_lines)
        snippet = f"\n--- FILE: {path} ---\n{file_snippet}\n"
        
        if char_budget - len(snippet) < 0:
            break
        source_context.append(snippet)
        char_budget -= len(snippet)

    errors_formatted = _format_errors_for_prompt(console_errors, network_errors)

    prompt = f"""You are an expert debugger. Analyze these runtime errors and map them to the source code.

RUNTIME ERRORS:
{errors_formatted}

SOURCE CODE:
{"".join(source_context)}

Return ONLY a valid JSON array (no markdown, no explanation) of bug objects.
Each object must have exactly these keys:
- "file": relative file path (string, e.g. "src/App.jsx")
- "line_number": approximate line number (integer or null)
- "error_type": short category like "ReferenceError", "TypeError", "NetworkError", "UndefinedVariable" etc.
- "error_description": clear one-sentence description of what's wrong
- "code_snippet": the problematic code (1-3 lines, string)
- "suggested_fix": the corrected code or clear instruction (string)
- "severity": one of "critical", "warning", "info"

If you cannot map an error to a specific file, still include it with file: "unknown".
Return an empty array [] if there are truly no bugs.

Example format:
[
  {{
    "file": "src/App.jsx",
    "line_number": 42,
    "error_type": "ReferenceError",
    "error_description": "Variable 'userData' is used before being defined",
    "code_snippet": "const name = userData.name;",
    "suggested_fix": "const userData = useUser(); // initialize before use",
    "severity": "critical"
  }}
]"""

    try:
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        bugs = _extract_json_array(response.text)
        # Validate and clean each bug object
        cleaned = []
        for bug in bugs:
            if not isinstance(bug, dict):
                continue
            cleaned.append({
                "file": str(bug.get("file", "unknown")),
                "line_number": bug.get("line_number"),
                "error_type": str(bug.get("error_type", "Error")),
                "error_description": str(bug.get("error_description", "Unknown error")),
                "code_snippet": str(bug.get("code_snippet", "")),
                "suggested_fix": str(bug.get("suggested_fix", "See error description")),
                "severity": bug.get("severity", "warning") if bug.get("severity") in ("critical", "warning", "info") else "warning",
            })
        return cleaned

    except Exception as e:
        print(f"[Auditor] LLM call failed: {e}")
        # Return raw errors as generic bugs so we still have something to show
        return [
            {
                "file": "unknown",
                "line_number": None,
                "error_type": err.get("type", "RuntimeError"),
                "error_description": err.get("text", "Unknown error")[:200],
                "code_snippet": "",
                "suggested_fix": "Investigate this error manually",
                "severity": "warning",
            }
            for err in console_errors[:5]
        ]


def _static_bug_scan(repo_path: str) -> list:
    """
    When no runtime errors exist, do a basic static scan for common issues.
    (console.log left in, TODO comments, missing error handling, etc.)
    """
    bugs = []
    source_files = _read_source_files(repo_path)

    for rel_path, content in source_files.items():
        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            # console.log left in production code
            if "console.log(" in stripped and not stripped.startswith("//"):
                bugs.append({
                    "file": rel_path,
                    "line_number": i,
                    "error_type": "DebugCode",
                    "error_description": "console.log() left in production code",
                    "code_snippet": stripped[:100],
                    "suggested_fix": "Remove console.log() before production deployment",
                    "severity": "info",
                })

            # TODO/FIXME comments
            if re.search(r"\b(TODO|FIXME|HACK|XXX)\b", stripped, re.IGNORECASE):
                bugs.append({
                    "file": rel_path,
                    "line_number": i,
                    "error_type": "UnfinishedCode",
                    "error_description": f"Unresolved {stripped[:50]}",
                    "code_snippet": stripped[:100],
                    "suggested_fix": "Address this TODO/FIXME before final release",
                    "severity": "info",
                })

        if len(bugs) >= 10:
            break

    return bugs
